# Generated by Django 5.0.7 on 2024-08-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='image',
        ),
    ]
